version: 'FYP-1'
services:
  webapp:
    build: ./apps/webapp
    ports:
      - "3000:3000"
    environment:
      - FYP_SERVER=http://backend:5010
    depends_on:
      - backend

  backend:
    build: ./apps/neuronpedia-fyp
    ports:
      - "5010:5010"