version: '3'
services:
  webapp:
    image: junhuigjh/neuronpedia-webapp
    ports:
      - "3000:3000"
    env_file:
      - .env

  backend:
    image: junhuigjh/neuronpedia-backend
    ports:
      - "5010:5010"
    env_file:
      - .env